### ISSUE TITLE
loading demo database in 4.1.1.

### ISSUE THREAD

**Issue by gpciceri** [sebastian-raubach/germinate-server#4]
Hi all,
after the setup , how can I load the demo database in my 4.1.1. instance? 
Is there a tutorial or should I follw the indications in the old 3.xx Wiki?

Thanks in advance.
/gp

**Comment by sebastian-raubach** [comment]
Hello,

We no longer support loading the demo data into a custom version of Germinate, because there didn't really seem to be a use-case for it.  People don't want to have the demo data in their database long term and for the short term exploration of the tool, we've got the demo database deployed for interactive exploration at https://ics.hutton.ac.uk/germinate-demo.

Having said that, you can load some exemplar data into your database using the examples in the [data template repository](https://github.com/germinateplatform/germinate-data-templates). Note that the germplasm MCPD data should always be loaded first.
This requires Gatekeeper to be set up though and some settings in the config file to be changed:

```ini
authentication.mode = <either 'SELECTIVE', 'FULL' or 'NONE'>
data.import.mode = <either 'IMPORT', 'VERIFY' OR 'NONE'>
```

The user within Gatekeeper has to be either an administrator for the Germinate database or a data curator for that user to be able to use the data import feature.

Hope this helps.

**Comment by gpciceri** [comment]
ok, so no easy way to have an instance up and running with an interface and some data in to play. 

please let me restate my situation.
I've 4.1.1. up from docker(s), with default home page (...this is the template text for the Germinate home page...), no idea how to get sample files for configuration (in the documentation is written the directory tree and few other fragments), no tutorial, no what-to-do-next guide (for release 4.1.1 at least).

may you please be so kind to tell me if there is a working configuration tree I can start with as an example? or perhaps I'm missing to see some other documentation, please be patient and let me point out where I can find it.

thanks in advance, best regards
/gp

**Comment by PrimettaFaccioli** [comment]
Dear Sebastian, many thanks for the help you are giving us. It is very important that we can start using Germinate with our germplasm collection.

**Comment by sebastian-raubach** [comment]
I've added some very preliminary documentation for [data upload](https://germinateplatform.github.io/germinate-server/dataimport.html) and I've specified some of the file names used for the logos on the [configuration page](https://germinateplatform.github.io/germinate-server/config.html)

I've also attached a file containing the Demo database config folder. Except the config file [demo-api.zip](https://github.com/germinateplatform/germinate-server/files/5505315/demo-api.zip)

**Comment by gpciceri** [comment]
thanks a lot,
now I have a gatekeeper up and running and an user: it's time to specificate a (not already existing) germinate database. In particular, what does the "Server" parameter mean? (is it a network name, an URL)?

Thanks in advance.
/gp

**Comment by sebastian-raubach** [comment]
Hi,
The server property is the MySQL server. The server and database settings should reflect whatever you are using in your `config.properties` as `database.server` and `database.name`.

**Comment by sebastian-raubach** [comment]
The next version of Gatekeeper will now include this: 
![2020-11-18 10_52_25-Gatekeeper](https://user-images.githubusercontent.com/12698452/99521344-35d14700-298c-11eb-8c35-ade9047b7c34.png)

**Comment by gpciceri** [comment]
ok - it seems to be up and running.

Thanks a lot.
/gp
